In [2]:
from PIL import Image
import os, glob
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
os.environ["PATH"] += os.pathsep + 'C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/bin'
os.environ["PATH"] += os.pathsep + 'C:/Program Files (x86)/Graphviz2.38/bin/'

In [5]:
import keras
from keras.models import Sequential
from keras.layers import Dense, LSTM
from keras.utils import np_utils

In [6]:
caltech_dir = "./image/101_ObjectCategories"

In [7]:
categories = ["chair", "camera", "butterfly", "elephant", "flamingo"]

In [8]:
nb_classed = len(categories)

In [9]:
Image_w = 64
Image_h = 64
pixels = Image_h * Image_w * 3

In [10]:
X = []
Y = []

for idx , cat in enumerate(categories):
    print(idx, cat)

0 chair
1 camera
2 butterfly
3 elephant
4 flamingo


In [11]:
X = []
Y = []

for idx , cat in enumerate(categories):
    label = [0 for i in range(nb_classed)]
    label[idx] = 1
    
    Image_dir = caltech_dir + "/" + cat
    files = glob.glob(Image_dir+"/*.jpg")
    for i, f in enumerate(files):
        img = Image.open(f)
        img = img.convert("RGB")
        img = img.resize((Image_w, Image_h))
        data = np.asarray(img)
        X.append(data)
        Y.append(label)
        if i % 10 == 0:
            print(i, "\n", data)
            

X = np.array(X)
Y = np.array(Y)

0 
 [[[255 250 251]
  [255 253 255]
  [254 253 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[254 255 255]
  [255 252 246]
  [255 254 243]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[239 245 245]
  [129 113  88]
  [156 131  91]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]
10 
 [[[207 187 188]
  [208 188 189]
  [206 186 185]
  ...
  [203 179 153]
  [201 177 151]
  [200 176 150]]

 [[208 188 187]
  [206 186 185]
  [209 190 186]
  ...
  [208 184 158]
  [204 180 154]
  [202 178 152]]

 [[204 185 181]
  [204 185 179]
  [204 185 179]
  ...
  [207 183 157]
  [203 179 153]
  [202 178 152]]

 ...

 [[233 220 212]
  [232 219 210]
  [229 217 

50 
 [[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
60 
 [[[180 148  99]
  [186 148  99]
  [237 201 149]
  ...
  [235 205 143]
  [223 193 131]
  [230 200 138]]

 [[187 150  95]
  [204 161 106]
  [224 184 125]
  ...
  [230 198 137]
  [227 195 134]
  [231 199 138]]

 [[199 162 107]
  [191 149  91]
  [223 185 123]
  ...
  [223 189 128]
  [229 195 134]
  [228 194 133]]

 ...

 [[239 195 132]
  [244 194 133]
  [242 194 132]
  ...
  [193 145  96]
  [186 139  87]
  [203 152  99]]

 [[240 196 131]
  [244 194 131]
  [241 193 129]
  ...
  [187 139  90]
  [195 148  96]
  [198 147  94]]

 [[233 190 122]
  [241 192 126]
  [240 192 126]
  

30 
 [[[237 234 215]
  [237 236 208]
  [239 234 212]
  ...
  [235 234 213]
  [238 237 207]
  [239 232 216]]

 [[236 237 206]
  [254 242 218]
  [255 246 192]
  ...
  [255 242 188]
  [248 232 207]
  [240 232 211]]

 [[234 236 212]
  [254 240 175]
  [197 174  62]
  ...
  [201 181  68]
  [255 238 195]
  [236 236 198]]

 ...

 [[236 233 226]
  [241 232 153]
  [217 205  35]
  ...
  [238 235  16]
  [255 247 159]
  [238 235 202]]

 [[239 237 212]
  [251 242 199]
  [255 250 168]
  ...
  [254 248 152]
  [246 236 209]
  [235 235 207]]

 [[235 232 213]
  [235 233 208]
  [236 239 196]
  ...
  [239 237 199]
  [235 236 204]
  [232 235 204]]]
40 
 [[[ 69  56  22]
  [ 66  56  21]
  [ 64  56  20]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[ 64  50  13]
  [ 69  57  19]
  [ 53  48   8]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[ 73  65  29]
  [ 69  65  28]
  [ 57  62  22]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[151 165 129]
  [140 156 119]
  [140 156

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X,Y)

xy = (X_train, X_test, y_train, y_test)
np.save("./image/5obj.npy", xy)

print("ok", len(Y))

ok 334
